typography_spectrum: 0.4756343262270093
color:
  brandColors:
    - '#FFFFFF'
    - '#F2E93B'
    - '#000000'
    - '#717171'
    - '#35570A'
  brandStrength: 0.7854074114002287
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5292574209161103
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/de9e51cd-7f42-4d7d-83ca-a95b460f6d52.png
name: Yellow Conference
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT YELLOW
    id: 1180ffe3-c6b9-4c9e-9a3c-14f879710cf8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f348b42-90b0-4d18-bee4-a57cd34c0758.png
purpose: []
