typography_spectrum: 0.6543118413537741
color:
  brandColors:
    - '#FFFFFF'
    - '#231F20'
    - '#FADB31'
    - '#5C5A5B'
    - '#B8B6B7'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.3622216205112636
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9136206605471671
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/de9e51cd-7f42-4d7d-83ca-a95b460f6d52.png
name: Yellow Conference
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT YELLOW
    id: 1180ffe3-c6b9-4c9e-9a3c-14f879710cf8
    type: content
  - name: Contact Us
    id: 252e04db-1c5c-4bcc-bd40-1f99620f027f
    type: content
  - name: JOIN The Grid Community
    url: 'https://thegrid.io/purchase/pause/'
    type: external
  - name: JOIN the Yellow Collective
    url: >-
      http://yellowconference.us3.list-manage.com/subscribe?u=3f8e45f74e0653e404965e2ef&id=e811fb1a74
    type: external
  - name: 'Buy Tickets '
    url: 'https://www.universe.com/events/yellow-conference-2016-tickets-F2Q869'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f348b42-90b0-4d18-bee4-a57cd34c0758.png
title: ''
purpose: []
